sudo: required
dist: trusty
language: node_js
git:
  depth: 10
node_js:
- iojs
before_install:
- export PATH=$(python -c 'from sys import argv;from collections import OrderedDict
  as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))'
  "$PATH")
- rvm install 2.2
- rvm use 2.2 --fuzzy
- gem install sass
install:
- bundle install --deployment --jobs=1
- cp grunt/npm-shrinkwrap.json ./
- npm install
cache:
  directories:
  - node_modules
  - vendor/bundle
env:
  global:
  - NPM_CONFIG_PROGRESS="false"
  - SAUCE_USERNAME="bootstrap"
  - secure: eEvUJnQgqW6cXNgtbX+AhgV5Zb169u+sr0MmoBSrO7i4tfw/QSLMtNlmf+RiR/yDkn5Zx8TIm0SeobhMTygjfh2vYFjr+WHqD65QZxvgKs2vdsVHVpnvhjigjO5IH+swVe27KX/A6RuBW92EKMybHG2Azm5ZGBl9ULJNq7wwgMeK+XdM4353sJy3JS3mdpBiiWm4oDuXCOx0BZXODSrHdkiK/0avpEstbFkwfU2+0lxGI25sCjm6b757jSTsBbzZplDgo0IzcyDeIngaP14LQSzi5lFELvxf6lyK+lKTBpp4+3SZNc6yM/L8+UonAolCUKkgp/PaBA8gpG4aon+Z1/fvdj2mXqsagJTMBn6lbxhGzrnlGgCms/LIg6Jgx8gK5nQd5wU1eE4vIVDhvG0abqwMDreVxuMLkRgudWSx2BSnBsJseBdIhVcvXRk0rxXtizT1g4pPqYioc5HfdjxmypJrctix/mtclMFnzICCwDtMddHS/k65I+FNmZ1GbW2hPjo36TT5PR9dCbM1t/Jj415W4qDmFSTBBHlFlegZeNHJtwT1Sh5Q1IgbO2uccvN0IF2Bwt1iR/HEbYRkwzfd+4/utw9V3oEf8SzIbJ2ZGChdpRuRrf+qwLzFTDJg3khJ3XJ6Pqtg93f9iStiAdqXja+FPY7dzEnTp2f/XKvvjKg=
  matrix:
  - TWBS_TEST=prep-release
  #- secure: WlP4D3cVn6zFhXkAs4IEUatCrV8DeT0G394KsE1gsXrpY7XpIzv90bDP/8MtalzhdeGOhhfddGNTSFM55hl9m5riwo1sAoeVeT80m++N5FFKOc/hFcBksDXxnG7ivicuyTjMNNNHJVFtVOh4a02kGKnY0rfiiJmSB2wiCHX6tPVgFDJKoX3Vb+66B8EX4rXh07s/I3pget1iwvc66LF+7yoi8MCK/KtSbyVKEnEXKK5CV/iP5CayNiOJT6SCtFpbMshvQoxYQMUxMh9U1pO6jQLj2t0GPae0T6Hu9DyvZgetZIk1+SqNDBYHfRq6uAAXbwq3YGzdnPq+DpIQgOhkuNGXnJK5X5rbVHadiCs86nq5HwI3hcxfDCxMtdBHi+dfiEI7vRGiZq2r5loz3Huq9r74tm6e2EuL+wZA6WvLpM44OXZ1VYdVVufwIpznPTjMt2wZPkroRrmd97e3iRJ2I3QYembdnayrrbLd5jNWPmXH4MoB++KVxgiJ2K8WfE3yczJmEMRu2RIO+F8S4LESchX/z2Waei0Rc8p/up/GRZIoKnltuDLKq6y2YLlp1ex3WMcWgX6bI9Xgq1P+xQ7jDQEiqQDclDQli/ZvDsug6C771aRE9Lm7/6reIGhop0FRXRQKGwXg/E/GMaPe3LWVOKaQiscMyOAG2la0pSVcYrQ=
matrix:
  fast_finish: true
notifications:
  slack: askanything:tSVB70CS7mqvrtFfQ8H0s12l
deploy:
  provider: pages
  skip_cleanup: true
  github_token: eEvUJnQgqW6cXNgtbX+AhgV5Zb169u+sr0MmoBSrO7i4tfw/QSLMtNlmf+RiR/yDkn5Zx8TIm0SeobhMTygjfh2vYFjr+WHqD65QZxvgKs2vdsVHVpnvhjigjO5IH+swVe27KX/A6RuBW92EKMybHG2Azm5ZGBl9ULJNq7wwgMeK+XdM4353sJy3JS3mdpBiiWm4oDuXCOx0BZXODSrHdkiK/0avpEstbFkwfU2+0lxGI25sCjm6b757jSTsBbzZplDgo0IzcyDeIngaP14LQSzi5lFELvxf6lyK+lKTBpp4+3SZNc6yM/L8+UonAolCUKkgp/PaBA8gpG4aon+Z1/fvdj2mXqsagJTMBn6lbxhGzrnlGgCms/LIg6Jgx8gK5nQd5wU1eE4vIVDhvG0abqwMDreVxuMLkRgudWSx2BSnBsJseBdIhVcvXRk0rxXtizT1g4pPqYioc5HfdjxmypJrctix/mtclMFnzICCwDtMddHS/k65I+FNmZ1GbW2hPjo36TT5PR9dCbM1t/Jj415W4qDmFSTBBHlFlegZeNHJtwT1Sh5Q1IgbO2uccvN0IF2Bwt1iR/HEbYRkwzfd+4/utw9V3oEf8SzIbJ2ZGChdpRuRrf+qwLzFTDJg3khJ3XJ6Pqtg93f9iStiAdqXja+FPY7dzEnTp2f/XKvvjKg=
  on:
    branch: v3-dev
