language: node_js

node_js:
- 6

before_install:
#  - export PATH=$(python -c 'from sys import argv;from collections import OrderedDict
#    as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))'
#    "$PATH")
  - rvm install 2.4.1
  - rvm use 2.4.1 --fuzzy
  - gem install jekyll
  - gem install bundler --pre

install:
  - bundle install --deployment --jobs=1
  - npm i -g gulp
  - npm install

before_script:
  - chmod +x ./deploy.sh

after_success:
  - gulp build
  - ./deploy.sh

after_failure:
  - exit 1

cache:
  directories:
  - node_modules
  - vendor/bundle

env:
  global:
  - NPM_CONFIG_PROGRESS="false"
  - secure: GH_TOKEN
  - secure: BNKLLtSN8qz/UuXv8c4V3vTi4FsK2epl0gn6S2iwuGdlAeUUK3vHsXDr2qMoGMSOjE9i+1+ijtmkRKfxcV3FmlYw3BwpanMkyVZGb3Jy6/cGRBcBOqf5IGMTtd+cv0ilR6s4eTMjR8QvBRLGgMWVjkkIQin5iB6ebbogmq0IF9CbxM3cSPTTagvNzPiFR1FMTmqP9Lpvze4xNOE+iN7/8ngiqG02RXZuH+eGUt3TWCekKkcsgt1g6e6PTXTse+vnTv86CmWlPSkrEbqhhYo9VaMYHk7A2e0zLK9BYOWGafNjqDHtODOtir+4I3gX/dpk7AIk9Jct3Cx5/Zl9+ST8FKPI+0cr2iHp9sAzmIUvWkpKmizGPiNDEoMtbANL0p7417XRfi8bxhFRmU0SN4PargY/6t9MDeVwzKDpZfyx4lR0xeCop0tYYtXtFhD10qPukuWZoA3XkGfJg3yWvt3UEgMlYguWYgckRUU+hjKUtzsIgoEG8vjG/7c26gGqDXGWF7UPKosCjmY6fo3/p58I3cBdYbvcEDBBURnKKbSeZ9xa7dHX9Z6C8CK1xn7EvrUQIWdlg9aRw1UmmOBorDGEO8mllno+rOWSe3JDKHGMFGkx6+He0t/XhVmLIZhUdvRFsfwGlHNZKjlgIWMi3ksODtWwh9O4T5bx0hjGW7IiMxw=
matrix:
  fast_finish: true
