sudo: required
dist: trusty
language: node_js
git:
  depth: 10
node_js:
- iojs
before_install:
- export PATH=$(python -c 'from sys import argv;from collections import OrderedDict
  as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))'
  "$PATH")
- rvm install 2.2
- rvm use 2.2 --fuzzy
- gem install sass
install:
- bundle install --deployment --jobs=1
- cp grunt/npm-shrinkwrap.json ./
- npm install
before_script:
  - chmod +x ./deploy.sh
after_success:
  - ./deploy.sh
cache:
  directories:
  - node_modules
  - vendor/bundle
env:
  global:
  - NPM_CONFIG_PROGRESS="false"
  - SAUCE_USERNAME="bootstrap"
  - secure: eEvUJnQgqW6cXNgtbX+AhgV5Zb169u+sr0MmoBSrO7i4tfw/QSLMtNlmf+RiR/yDkn5Zx8TIm0SeobhMTygjfh2vYFjr+WHqD65QZxvgKs2vdsVHVpnvhjigjO5IH+swVe27KX/A6RuBW92EKMybHG2Azm5ZGBl9ULJNq7wwgMeK+XdM4353sJy3JS3mdpBiiWm4oDuXCOx0BZXODSrHdkiK/0avpEstbFkwfU2+0lxGI25sCjm6b757jSTsBbzZplDgo0IzcyDeIngaP14LQSzi5lFELvxf6lyK+lKTBpp4+3SZNc6yM/L8+UonAolCUKkgp/PaBA8gpG4aon+Z1/fvdj2mXqsagJTMBn6lbxhGzrnlGgCms/LIg6Jgx8gK5nQd5wU1eE4vIVDhvG0abqwMDreVxuMLkRgudWSx2BSnBsJseBdIhVcvXRk0rxXtizT1g4pPqYioc5HfdjxmypJrctix/mtclMFnzICCwDtMddHS/k65I+FNmZ1GbW2hPjo36TT5PR9dCbM1t/Jj415W4qDmFSTBBHlFlegZeNHJtwT1Sh5Q1IgbO2uccvN0IF2Bwt1iR/HEbYRkwzfd+4/utw9V3oEf8SzIbJ2ZGChdpRuRrf+qwLzFTDJg3khJ3XJ6Pqtg93f9iStiAdqXja+FPY7dzEnTp2f/XKvvjKg=
  matrix:
  - TWBS_TEST=test
  - TWBS_TEST=prep-release
matrix:
  fast_finish: true
notifications:
  slack: askanything:tSVB70CS7mqvrtFfQ8H0s12l
deploy:
  provider: pages
  skip_cleanup: true
  github_token: eEvUJnQgqW6cXNgtbX+AhgV5Zb169u+sr0MmoBSrO7i4tfw/QSLMtNlmf+RiR/yDkn5Zx8TIm0SeobhMTygjfh2vYFjr+WHqD65QZxvgKs2vdsVHVpnvhjigjO5IH+swVe27KX/A6RuBW92EKMybHG2Azm5ZGBl9ULJNq7wwgMeK+XdM4353sJy3JS3mdpBiiWm4oDuXCOx0BZXODSrHdkiK/0avpEstbFkwfU2+0lxGI25sCjm6b757jSTsBbzZplDgo0IzcyDeIngaP14LQSzi5lFELvxf6lyK+lKTBpp4+3SZNc6yM/L8+UonAolCUKkgp/PaBA8gpG4aon+Z1/fvdj2mXqsagJTMBn6lbxhGzrnlGgCms/LIg6Jgx8gK5nQd5wU1eE4vIVDhvG0abqwMDreVxuMLkRgudWSx2BSnBsJseBdIhVcvXRk0rxXtizT1g4pPqYioc5HfdjxmypJrctix/mtclMFnzICCwDtMddHS/k65I+FNmZ1GbW2hPjo36TT5PR9dCbM1t/Jj415W4qDmFSTBBHlFlegZeNHJtwT1Sh5Q1IgbO2uccvN0IF2Bwt1iR/HEbYRkwzfd+4/utw9V3oEf8SzIbJ2ZGChdpRuRrf+qwLzFTDJg3khJ3XJ6Pqtg93f9iStiAdqXja+FPY7dzEnTp2f/XKvvjKg=
  on:
    branch: master
    target_branch: gh-pages
