sudo: required
dist: trusty
language: node_js
git:
  depth: 10
node_js:
- iojs
before_install:
- export PATH=$(python -c 'from sys import argv;from collections import OrderedDict
  as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))'
  "$PATH")
- rvm install 2.2
- rvm use 2.2 --fuzzy
- gem install sass
install:
- bundle install --deployment --jobs=1
- cp grunt/npm-shrinkwrap.json ./
- npm install
before_script:
- chmod +x ./deploy.sh
after_success:
- npm run prep-release
- "./deploy.sh"
cache:
  directories:
  - node_modules
  - vendor/bundle
env:
  global:
  - NPM_CONFIG_PROGRESS="false"
  - SAUCE_USERNAME="bootstrap"
  - secure: GH_TOKEN
  - secure: ZmSlRw9CVWWdcp5hRfR91qxSGUPkQ1/fYhw3MW6OIcQi397XA1S6dAUIdSlQz4sA6SdNkgsWERkCsLXeAJ1q4muXy8tNYIK50IuevDm2eoL9w4mLGM8Ld+z8Kdx0d0iVAogvaSBTbh+eiN+QTjvV3s32S/hszFVx3o3gM6lOLyVC0Mvrz7BeJj8hFJZzg/zgLmZUzATzk/wooqro/B725jPjR0jK5ztMI5kxyn+v7Aby+e+0rDUVveHHW0tT9whgxvObTG5mXfvN22zBMKRoT0ucIQJD2ZP1g7qY55StgcHIfLCVx459VAKAkMCjqx+3sfBmd4kXHZuZVer7vJVkjdvCsQWqpLExIHSn80Ba6pVKXlsM0JSrnXDxKDQl98FuRGbirCEeXQsmFoF1yywXBp9mTVkP6Pg8wgFN0fao9xgLfIBlGcRPnmeoT+2bxwYeW5gkFt95h+R1kper6iLPiJrlwxYNFJpJ6wneuCXljN/kz+p2HrGXzpYdCw9qaZWjJhYbAmYYb+Ykiug3OAPH5xfhKJSJJb53EzuGzlR1iSLIOTsofwba6genApBlycTv8xOUiX+PYUh8YvdYwHIOrLTfolDj9jy2V63pnWnFmi5wWP/8QSLSCAr3oiHDqhjZBbw3OLd4mG4Tg3AZCQpCKn9xmzSX+c6b2ce+7dGex7Q=
matrix:
  fast_finish: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ZmSlRw9CVWWdcp5hRfR91qxSGUPkQ1/fYhw3MW6OIcQi397XA1S6dAUIdSlQz4sA6SdNkgsWERkCsLXeAJ1q4muXy8tNYIK50IuevDm2eoL9w4mLGM8Ld+z8Kdx0d0iVAogvaSBTbh+eiN+QTjvV3s32S/hszFVx3o3gM6lOLyVC0Mvrz7BeJj8hFJZzg/zgLmZUzATzk/wooqro/B725jPjR0jK5ztMI5kxyn+v7Aby+e+0rDUVveHHW0tT9whgxvObTG5mXfvN22zBMKRoT0ucIQJD2ZP1g7qY55StgcHIfLCVx459VAKAkMCjqx+3sfBmd4kXHZuZVer7vJVkjdvCsQWqpLExIHSn80Ba6pVKXlsM0JSrnXDxKDQl98FuRGbirCEeXQsmFoF1yywXBp9mTVkP6Pg8wgFN0fao9xgLfIBlGcRPnmeoT+2bxwYeW5gkFt95h+R1kper6iLPiJrlwxYNFJpJ6wneuCXljN/kz+p2HrGXzpYdCw9qaZWjJhYbAmYYb+Ykiug3OAPH5xfhKJSJJb53EzuGzlR1iSLIOTsofwba6genApBlycTv8xOUiX+PYUh8YvdYwHIOrLTfolDj9jy2V63pnWnFmi5wWP/8QSLSCAr3oiHDqhjZBbw3OLd4mG4Tg3AZCQpCKn9xmzSX+c6b2ce+7dGex7Q=
  on:
    branch: gh-pages
