sudo: required
language: node_js
#group: deprecated-2017Q3
#git:
#  depth: 10
node_js:
  - 6
before_install:
  - export PATH=$(python -c 'from sys import argv;from collections import OrderedDict
    as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))'
    "$PATH")
  - rvm install 2.4.1
  - rvm use 2.4.1 --fuzzy
  - gem install bundler
  #- gem install sass
install:
  - bundle install --deployment --jobs=1
  #- cp grunt/npm-shrinkwrap.json ./
  - npm install
before_script:
  - chmod +x ./deploy.sh
after_success:
  - gulp prep-release
  #- npm run prep-release
  # - "./deploy.sh"
cache:
  directories:
  - node_modules
  - vendor/bundle
env:
  global:
  - NPM_CONFIG_PROGRESS="false"
  #- SAUCE_USERNAME="bootstrap"
  - secure: GH_TOKEN
  #- secure: ZmSlRw9CVWWdcp5hRfR91qxSGUPkQ1/fYhw3MW6OIcQi397XA1S6dAUIdSlQz4sA6SdNkgsWERkCsLXeAJ1q4muXy8tNYIK50IuevDm2eoL9w4mLGM8Ld+z8Kdx0d0iVAogvaSBTbh+eiN+QTjvV3s32S/hszFVx3o3gM6lOLyVC0Mvrz7BeJj8hFJZzg/zgLmZUzATzk/wooqro/B725jPjR0jK5ztMI5kxyn+v7Aby+e+0rDUVveHHW0tT9whgxvObTG5mXfvN22zBMKRoT0ucIQJD2ZP1g7qY55StgcHIfLCVx459VAKAkMCjqx+3sfBmd4kXHZuZVer7vJVkjdvCsQWqpLExIHSn80Ba6pVKXlsM0JSrnXDxKDQl98FuRGbirCEeXQsmFoF1yywXBp9mTVkP6Pg8wgFN0fao9xgLfIBlGcRPnmeoT+2bxwYeW5gkFt95h+R1kper6iLPiJrlwxYNFJpJ6wneuCXljN/kz+p2HrGXzpYdCw9qaZWjJhYbAmYYb+Ykiug3OAPH5xfhKJSJJb53EzuGzlR1iSLIOTsofwba6genApBlycTv8xOUiX+PYUh8YvdYwHIOrLTfolDj9jy2V63pnWnFmi5wWP/8QSLSCAr3oiHDqhjZBbw3OLd4mG4Tg3AZCQpCKn9xmzSX+c6b2ce+7dGex7Q=
  - secure: BNKLLtSN8qz/UuXv8c4V3vTi4FsK2epl0gn6S2iwuGdlAeUUK3vHsXDr2qMoGMSOjE9i+1+ijtmkRKfxcV3FmlYw3BwpanMkyVZGb3Jy6/cGRBcBOqf5IGMTtd+cv0ilR6s4eTMjR8QvBRLGgMWVjkkIQin5iB6ebbogmq0IF9CbxM3cSPTTagvNzPiFR1FMTmqP9Lpvze4xNOE+iN7/8ngiqG02RXZuH+eGUt3TWCekKkcsgt1g6e6PTXTse+vnTv86CmWlPSkrEbqhhYo9VaMYHk7A2e0zLK9BYOWGafNjqDHtODOtir+4I3gX/dpk7AIk9Jct3Cx5/Zl9+ST8FKPI+0cr2iHp9sAzmIUvWkpKmizGPiNDEoMtbANL0p7417XRfi8bxhFRmU0SN4PargY/6t9MDeVwzKDpZfyx4lR0xeCop0tYYtXtFhD10qPukuWZoA3XkGfJg3yWvt3UEgMlYguWYgckRUU+hjKUtzsIgoEG8vjG/7c26gGqDXGWF7UPKosCjmY6fo3/p58I3cBdYbvcEDBBURnKKbSeZ9xa7dHX9Z6C8CK1xn7EvrUQIWdlg9aRw1UmmOBorDGEO8mllno+rOWSe3JDKHGMFGkx6+He0t/XhVmLIZhUdvRFsfwGlHNZKjlgIWMi3ksODtWwh9O4T5bx0hjGW7IiMxw=
matrix:
  fast_finish: true
